#spring:
#  kafka:
#    bootstrap-servers:
#    - 192.168.1.18:9092
#    - 192.168.1.13:9092
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  bootstrap:
    servers: 192.168.1.18:9092,192.168.1.13:9092
        
